name: Run CI
on:
  push

jobs:
  test:
    strategy:
      matrix:
        os: [ windows-2019 ]
        node: [ "18" ]

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Build 
        run: |
          npm install
          npm test
