name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  prebuild:
    strategy:
      matrix:
        os: [ macos-11, ubuntu-20.04, windows-2019 ]
        node: [ 16.13.0 ]
        runtime: [ node ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Configure msvs version on Windows
        if: ${{matrix.os == 'windows-2019'}}
        run: npm config set msvs_version 2019
      - name: Install
        run: npm ci --unsafe-perm
      - name: Prebuild 
        shell: bash
        run: |
          npm run build-tesseract
          npm run create-prebuild -- -u ${{ secrets.REPO_TOKEN }}
      - name: List prebuilds
        shell: bash
        run: ls -la ./prebuilds

  deploy:
    needs:
      - prebuild
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install
        run: npm ci --unsafe-perm
      - name: Build
        run: npm run build-js
      - name: Publish tagged release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_RELEASE_PUBLISH_TOKEN }}
